// Known disposable / temporary email providers, blocked at signup.
// Checked against the full domain and every parent domain, so
// anything@sub.mailinator.com is caught by the "mailinator.com" entry.
// Mirror any additions in supabase/blocked-email-domains.sql (DB-level backstop).
const DISPOSABLE_DOMAINS = new Set([
  // Mailinator family
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailinater.com",
  "binkmail.com",
  "bobmail.info",
  "chammy.info",
  "suremail.info",
  "safetymail.info",
  "sogetthis.com",
  "spamherelots.com",
  "thisisnotmyrealemail.com",
  // Guerrilla Mail family
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamailblock.com",
  "grr.la",
  "sharklasers.com",
  "pokemail.net",
  "spam4.me",
  // 10 Minute Mail & minute-mail clones
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.co.uk",
  "10minemail.com",
  "10mail.org",
  "20minutemail.com",
  "minuteinbox.com",
  "10minutesemail.net",
  // Temp-mail family
  "temp-mail.org",
  "temp-mail.io",
  "temp-mail.ru",
  "tempmail.com",
  "tempmail.net",
  "tempmail.dev",
  "tempmailo.com",
  "tempmailaddress.com",
  "tempail.com",
  "tempr.email",
  "tempinbox.com",
  "tmpmail.org",
  "tmpmail.net",
  "tmpeml.com",
  "tmail.ws",
  "mytemp.email",
  "mail-temp.com",
  // YOPmail family
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "cool.fr.nf",
  "jetable.fr.nf",
  "courriel.fr.nf",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  // Trashmail family
  "trashmail.com",
  "trashmail.de",
  "trashmail.net",
  "trashmail.me",
  "trash-mail.com",
  "trash-mail.de",
  "kurzepost.de",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "mytrashmail.com",
  // Other widely used services
  "1secmail.com",
  "1secmail.org",
  "1secmail.net",
  "33mail.com",
  "abyssmail.com",
  "anonbox.net",
  "anonymbox.com",
  "burnermail.io",
  "byom.de",
  "crazymailing.com",
  "deadaddress.com",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "dispostable.com",
  "dropmail.me",
  "emailfake.com",
  "emailondeck.com",
  "emailsensei.com",
  "emltmp.com",
  "fakeinbox.com",
  "fakemailgenerator.com",
  "getairmail.com",
  "getnada.com",
  "harakirimail.com",
  "inboxbear.com",
  "inboxkitten.com",
  "incognitomail.com",
  "jetable.org",
  "mail.tm",
  "mail7.io",
  "mailcatch.com",
  "maildrop.cc",
  "maildu.de",
  "mailexpire.com",
  "mailhazard.com",
  "mailnesia.com",
  "mailpoof.com",
  "mailsac.com",
  "mailslurp.com",
  "meltmail.com",
  "mintemail.com",
  "moakt.com",
  "moakt.cc",
  "mohmal.com",
  "muellmail.com",
  "mvrht.com",
  "nada.email",
  "no-spam.ws",
  "nospam.ze.tc",
  "nowmymail.com",
  "objectmail.com",
  "obobbo.com",
  "onewaymail.com",
  "owlymail.com",
  "proxymail.eu",
  "rcpt.at",
  "receiveee.com",
  "rhyta.com",
  "sendspamhere.com",
  "spam.la",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spambox.us",
  "spamex.com",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.org",
  "spamgourmet.com",
  "spamhole.com",
  "spaml.com",
  "spamspot.com",
  "speed.1s.fr",
  "supermailer.jp",
  "teleworm.us",
  "temporarymail.com",
  "throwawaymail.com",
  "tradermail.info",
  "trbvm.com",
  "trickmail.net",
  "veryrealemail.com",
  "webemail.me",
  "wh4f.org",
  "whyspam.me",
  "willselfdestruct.com",
  "winemaven.info",
  "wuzup.net",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xmaily.com",
  "yep.it",
  "yogamaven.com",
  "yuurok.com",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoemail.net",
]);

export function getEmailDomain(email: string): string {
  return email.trim().toLowerCase().split("@").pop() ?? "";
}

export function isDisposableEmail(email: string): boolean {
  const domain = getEmailDomain(email);
  if (!domain) return false;

  // Check the domain itself and every parent domain
  const parts = domain.split(".");
  for (let i = 0; i < parts.length - 1; i++) {
    if (DISPOSABLE_DOMAINS.has(parts.slice(i).join("."))) return true;
  }
  return false;
}
