import type { Question, Section } from "./types";

export const SECTIONS: Section[] = [
  {
    id: 1,
    title: "Boundary Firewalls & Internet Gateways",
    shortTitle: "Firewalls",
    description: "Understand whether your business has suitable protections between your internal systems and the internet.",
  },
  {
    id: 2,
    title: "Secure Configuration",
    shortTitle: "Configuration",
    description: "Check whether devices, systems, and software are configured securely before they are used.",
  },
  {
    id: 3,
    title: "User Access Control",
    shortTitle: "Access Control",
    description: "Review who has access to your systems and whether permissions are appropriate.",
  },
  {
    id: 4,
    title: "Malware Protection",
    shortTitle: "Malware",
    description: "Understand whether your devices are protected from malware and unsafe applications.",
  },
  {
    id: 5,
    title: "Security Update Management",
    shortTitle: "Updates",
    description: "Check whether your business keeps software and devices updated against known vulnerabilities.",
  },
];

const YES_NO: Question["options"] = [
  { value: "yes", label: "Yes" },
  { value: "no", label: "No" },
  { value: "partial", label: "Partially — some but not all" },
  { value: "unsure", label: "I am not sure" },
];

const YES_NO_SIMPLE: Question["options"] = [
  { value: "yes", label: "Yes" },
  { value: "no", label: "No" },
  { value: "unsure", label: "I am not sure" },
];

export const QUESTIONS: Question[] = [

  // ── Section 1: Firewalls ─────────────────────────────────────────────────
  {
    key: "fw_firewall_in_place",
    sectionId: 1,
    text: "Does your organisation have a firewall in place to protect its internet connection?",
    hint: "This includes routers provided by your internet service provider if they include firewall functionality",
    whyWeAsk: "A firewall is the first line of defence between your internal systems and the internet. Cyber Essentials requires that all internet connections are protected by a firewall or equivalent boundary device.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "fw_default_passwords_changed",
    sectionId: 1,
    text: "Have the default administrator passwords on your firewalls or routers been changed to something unique?",
    hint: "Default passwords are publicly known and must be changed before deployment",
    whyWeAsk: "Devices shipped with default credentials are easily compromised. Cyber Essentials requires that all default passwords are changed before a device is put into service.",
    type: "radio",
    options: YES_NO_SIMPLE,
  },
  {
    key: "fw_inbound_rules_reviewed",
    sectionId: 1,
    text: "Are your firewall rules reviewed regularly to ensure only necessary inbound connections are permitted?",
    hint: "Unused or unnecessary inbound rules increase your attack surface",
    whyWeAsk: "Cyber Essentials requires that firewalls block all inbound connections that are not explicitly needed for business operations.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "fw_services_exposed",
    sectionId: 1,
    text: "Does your organisation expose any services directly to the internet (such as remote desktop, file sharing, or admin interfaces)?",
    hint: "Exposed services require specific protective controls under Cyber Essentials",
    whyWeAsk: "Exposing services directly to the internet without controls is a common attack vector. Cyber Essentials requires that unnecessary services are not accessible from the internet.",
    type: "radio",
    options: YES_NO_SIMPLE,
  },
  {
    key: "fw_cloud_security_groups",
    sectionId: 1,
    text: "If you use cloud services, are network security groups or equivalent controls configured to restrict access?",
    hint: "Cloud-hosted services are in scope for Cyber Essentials if they process business data",
    whyWeAsk: "Cloud environments need the same boundary controls as on-premises networks. Security groups or access control lists must be configured to restrict unnecessary inbound access.",
    type: "radio",
    options: [
      { value: "yes", label: "Yes, we use cloud services and they are protected" },
      { value: "no", label: "We use cloud services but they are not protected this way" },
      { value: "not_applicable", label: "We do not use cloud services" },
      { value: "unsure", label: "I am not sure" },
    ],
  },
  {
    key: "fw_network_boundary_documented",
    sectionId: 1,
    text: "Do you have a documented understanding of which devices connect to the internet and how they are protected?",
    hint: "This does not need to be a formal network diagram — a simple list is acceptable",
    whyWeAsk: "Knowing your network boundary is essential to applying the right protections. Cyber Essentials requires that organisations understand what is in scope and what connects to the internet.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "fw_vpn_mfa",
    sectionId: 1,
    text: "If staff connect remotely to your systems, is multi-factor authentication required for that access?",
    hint: "VPNs, remote desktop services, and cloud portals all count as remote access",
    whyWeAsk: "Remote access without MFA is one of the most common causes of breaches. Cyber Essentials requires that all remote access to internal systems is protected with MFA.",
    type: "radio",
    options: [
      { value: "yes", label: "Yes, MFA is required" },
      { value: "no", label: "No, MFA is not required" },
      { value: "partial", label: "MFA is used by some staff but not all" },
      { value: "not_applicable", label: "We do not have remote access" },
    ],
  },
  {
    key: "fw_wifi_separation",
    sectionId: 1,
    text: "Is your guest Wi-Fi network separated from your internal business network?",
    hint: "Guest Wi-Fi should not allow access to business systems or data",
    whyWeAsk: "Without separation, a guest or attacker on your Wi-Fi could access internal systems. Cyber Essentials requires that guest networks are isolated from business systems.",
    type: "radio",
    options: [
      { value: "yes", label: "Yes, they are separated" },
      { value: "no", label: "No, they are on the same network" },
      { value: "no_guest", label: "We do not offer guest Wi-Fi" },
      { value: "unsure", label: "I am not sure" },
    ],
  },
  {
    key: "fw_unnecessary_ports_closed",
    sectionId: 1,
    text: "Are unnecessary ports and services disabled or blocked on your network boundary devices?",
    hint: "Ports are communication channels — open but unused ports are a security risk",
    whyWeAsk: "Open and unused ports can be exploited by attackers. Cyber Essentials requires that only necessary ports are permitted through boundary firewalls.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "fw_isp_router_reviewed",
    sectionId: 1,
    text: "Have you reviewed the security settings of your internet service provider's router or modem?",
    hint: "Many ISP-provided routers have weak default settings that can be improved",
    whyWeAsk: "ISP-provided routers are part of your network boundary. Cyber Essentials requires that boundary devices are appropriately configured, including those provided by third parties.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "fw_firewall_logging",
    sectionId: 1,
    text: "Does your firewall or router log traffic, and are those logs reviewed?",
    hint: "Logging is not mandatory for Cyber Essentials but is good practice",
    whyWeAsk: "Firewall logs help detect unusual activity. While not strictly required for Cyber Essentials, they indicate a more mature security posture and support breach detection.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "fw_responsibility_clear",
    sectionId: 1,
    text: "Is someone in your organisation responsible for managing and maintaining your firewall settings?",
    hint: "This could be internal IT, an outsourced provider, or an MSP",
    whyWeAsk: "Clear ownership of firewall management is essential for maintaining controls over time. Cyber Essentials requires that appropriate controls are actively maintained.",
    type: "radio",
    options: YES_NO_SIMPLE,
  },

  // ── Section 2: Secure Configuration ─────────────────────────────────────
  {
    key: "sc_default_credentials_changed",
    sectionId: 2,
    text: "Are all default usernames and passwords changed on devices and software before use?",
    hint: "This applies to computers, servers, routers, printers, and cloud services",
    whyWeAsk: "Default credentials are widely known and are one of the first things attackers try. Cyber Essentials requires that all defaults are changed before a system is put into production use.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_unused_software_removed",
    sectionId: 2,
    text: "Is software that is not required for business purposes removed or disabled?",
    hint: "This includes pre-installed software, trial applications, and legacy tools",
    whyWeAsk: "Unused software can contain vulnerabilities that attackers exploit. Cyber Essentials requires that unnecessary software is removed to reduce the attack surface.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_auto_run_disabled",
    sectionId: 2,
    text: "Is the auto-run or auto-play feature disabled on devices where it is not needed?",
    hint: "Auto-run can automatically execute malicious code from USB drives or CDs",
    whyWeAsk: "Auto-run features have been exploited to spread malware via physical media. Cyber Essentials recommends that auto-run is disabled on all devices.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_screen_lock_enabled",
    sectionId: 2,
    text: "Are all devices configured to lock automatically after a period of inactivity?",
    hint: "Industry guidance suggests a maximum of 10 minutes before automatic lock",
    whyWeAsk: "Unlocked devices left unattended are a simple way for attackers to gain access. Cyber Essentials requires that all devices have an automatic lock enabled.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_encryption_enabled",
    sectionId: 2,
    text: "Are devices that store business data encrypted?",
    hint: "This applies to laptops, tablets, smartphones, and portable storage",
    whyWeAsk: "Encryption protects data if a device is lost or stolen. Cyber Essentials Plus requires full-disk encryption, and it is good practice for the standard assessment.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_secure_boot_enabled",
    sectionId: 2,
    text: "Is Secure Boot enabled on devices where it is available?",
    hint: "Secure Boot prevents unauthorised code from loading during startup",
    whyWeAsk: "Secure Boot protects against certain classes of malware that target the startup process. Cyber Essentials recommends that Secure Boot is enabled where supported.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_cloud_services_configured",
    sectionId: 2,
    text: "Are your cloud services configured securely, including removing unnecessary features and default settings?",
    hint: "Cloud platforms like Microsoft 365 and Google Workspace have many security settings that should be reviewed",
    whyWeAsk: "Cloud services are frequently misconfigured, exposing business data. Cyber Essentials requires that cloud services are reviewed and hardened in the same way as on-premises systems.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_device_inventory",
    sectionId: 2,
    text: "Does your organisation maintain an up-to-date list of all devices used for business purposes?",
    hint: "Including laptops, desktops, mobile phones, tablets, and any cloud-connected devices",
    whyWeAsk: "You cannot secure what you do not know about. An asset inventory is a fundamental prerequisite for consistent configuration management.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_software_inventory",
    sectionId: 2,
    text: "Do you know what software is installed across your business devices?",
    hint: "Including operating systems, office tools, browsers, and any specialist applications",
    whyWeAsk: "Knowing what software is installed is essential for keeping it updated and removing unnecessary applications. Cyber Essentials requires organisations to understand what software is in use.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_consistent_baseline",
    sectionId: 2,
    text: "Do new devices follow a consistent secure baseline configuration before being given to users?",
    hint: "A baseline might cover screen lock, encryption, software installations, and user accounts",
    whyWeAsk: "Without a consistent baseline, devices are set up differently and some may miss key security settings. Cyber Essentials requires that devices are configured consistently and securely.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_unnecessary_features_disabled",
    sectionId: 2,
    text: "Are unnecessary features and services disabled on your devices and servers?",
    hint: "Such as file sharing, remote desktop, Bluetooth when not needed, or unused network protocols",
    whyWeAsk: "Unused features and services can be exploited by attackers. Cyber Essentials requires that only the features needed for business are enabled.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "sc_config_review_frequency",
    sectionId: 2,
    text: "Are your device and system configurations reviewed periodically to check they remain appropriate?",
    hint: "Annual review is considered good practice for most SMEs",
    whyWeAsk: "Configuration drift is common — settings change over time as software is updated or new tools are added. Regular reviews ensure security settings remain appropriate.",
    type: "radio",
    options: YES_NO,
  },

  // ── Section 3: User Access Control ──────────────────────────────────────
  {
    key: "ua_least_privilege",
    sectionId: 3,
    text: "Are users given only the access rights they need to do their job?",
    hint: "This is the principle of least privilege — no more access than necessary",
    whyWeAsk: "Excessive access rights mean that if an account is compromised, the attacker gains more capability. Cyber Essentials requires that users are given only the access they need.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "ua_admin_accounts_limited",
    sectionId: 3,
    text: "Are administrator accounts limited to the staff who genuinely need them?",
    hint: "Administrator accounts should only be used for administrative tasks, not everyday work",
    whyWeAsk: "Admin accounts have more power and are a higher-value target. Cyber Essentials requires that admin accounts are limited in number and used only for administrative purposes.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "ua_separate_admin_accounts",
    sectionId: 3,
    text: "Do administrators have separate accounts for administrative tasks and for everyday work?",
    hint: "Using an admin account for daily tasks like email or browsing increases risk",
    whyWeAsk: "Using admin accounts for everyday tasks exposes privileged credentials to greater risk. Cyber Essentials requires that admin activity is separated from standard user activity.",
    type: "radio",
    options: YES_NO_SIMPLE,
  },
  {
    key: "ua_mfa_enabled",
    sectionId: 3,
    text: "Is multi-factor authentication (MFA) enabled for accounts that access business systems?",
    hint: "Particularly for email, cloud services, remote access, and administrative accounts",
    whyWeAsk: "MFA significantly reduces the risk of account compromise even if a password is stolen. Cyber Essentials strongly recommends MFA, and it is now required for remote access.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "ua_leavers_process",
    sectionId: 3,
    text: "Is there a process to remove or disable accounts when someone leaves your organisation?",
    hint: "Including email accounts, cloud service access, and physical system access",
    whyWeAsk: "Active accounts for ex-employees are a common and easily avoidable security risk. Cyber Essentials requires that accounts are promptly removed when no longer needed.",
    type: "radio",
    options: YES_NO_SIMPLE,
  },
  {
    key: "ua_guest_accounts_removed",
    sectionId: 3,
    text: "Are guest, shared, or default user accounts removed or disabled on your systems?",
    hint: "Default accounts such as 'Guest', 'Admin', or 'Administrator' should be removed or renamed",
    whyWeAsk: "Generic or default accounts are easy targets for attackers because they are predictable. Cyber Essentials requires that unnecessary accounts are removed.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "ua_password_policy",
    sectionId: 3,
    text: "Does your organisation use a password policy that requires appropriately strong passwords?",
    hint: "NCSC recommends using three random words as an approach for users — length matters more than complexity",
    whyWeAsk: "Weak passwords are easily guessed or cracked. Cyber Essentials requires that accounts are protected with appropriately strong passwords or equivalent controls.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "ua_access_review",
    sectionId: 3,
    text: "Are user access rights reviewed regularly to check they remain appropriate?",
    hint: "Particularly when someone changes role or responsibility within the organisation",
    whyWeAsk: "Access rights can accumulate over time. Cyber Essentials requires that access is reviewed to ensure it remains appropriate as people change roles.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "ua_privileged_software_install",
    sectionId: 3,
    text: "Are standard users prevented from installing software without administrator approval?",
    hint: "Users should not be able to install applications freely on business devices",
    whyWeAsk: "Allowing users to install software freely introduces the risk of malware or unauthorised applications. Cyber Essentials requires that software installation is controlled.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "ua_password_manager",
    sectionId: 3,
    text: "Is a password manager used to help staff create and store strong, unique passwords?",
    hint: "Password managers reduce password reuse across accounts",
    whyWeAsk: "Password reuse is a significant risk. Where MFA is not available, strong unique passwords managed by a password manager significantly reduce risk.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "ua_account_lockout",
    sectionId: 3,
    text: "Are accounts configured to lock after a number of failed login attempts?",
    hint: "Typically after 5 to 10 failed attempts",
    whyWeAsk: "Account lockout policies prevent automated brute-force attacks. Cyber Essentials recommends that all accounts are protected by account lockout or equivalent controls.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "ua_third_party_access",
    sectionId: 3,
    text: "Is third-party or supplier access to your systems reviewed and controlled?",
    hint: "Including IT providers, software vendors, or external contractors",
    whyWeAsk: "Third-party access is a common attack vector. Access granted to external parties should be limited, monitored, and removed when no longer needed.",
    type: "radio",
    options: [
      { value: "yes", label: "Yes, third-party access is controlled" },
      { value: "no", label: "No, we do not manage this formally" },
      { value: "not_applicable", label: "We do not grant third-party access" },
      { value: "unsure", label: "I am not sure" },
    ],
  },

  // ── Section 4: Malware Protection ────────────────────────────────────────
  {
    key: "mp_antimalware_installed",
    sectionId: 4,
    text: "Is anti-malware software installed on all devices used for business purposes?",
    hint: "Including laptops, desktops, and servers — mobile devices may be covered separately",
    whyWeAsk: "Anti-malware is a core requirement of Cyber Essentials. All devices that could be exposed to malware must have appropriate protection installed.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "mp_antimalware_updated",
    sectionId: 4,
    text: "Is your anti-malware software kept up to date automatically?",
    hint: "Anti-malware must be updated regularly — ideally daily — to detect the latest threats",
    whyWeAsk: "Anti-malware that is not updated quickly becomes ineffective. Cyber Essentials requires that anti-malware definitions are kept current to detect new threats.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "mp_realtime_scanning",
    sectionId: 4,
    text: "Is real-time scanning enabled on all devices covered by anti-malware?",
    hint: "Real-time scanning checks files and downloads as they are accessed, not just during scheduled scans",
    whyWeAsk: "Scheduled scans alone may miss threats that are active between scans. Real-time scanning provides continuous protection and is required by Cyber Essentials.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "mp_web_filtering",
    sectionId: 4,
    text: "Is web filtering or browser protection in place to prevent access to known malicious websites?",
    hint: "Many anti-malware suites include this feature, as does Microsoft Defender SmartScreen",
    whyWeAsk: "Malicious websites are a common malware delivery mechanism. Web filtering reduces the risk of users inadvertently downloading malware through their browser.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "mp_email_filtering",
    sectionId: 4,
    text: "Is email filtering in place to detect and block malicious attachments and phishing links?",
    hint: "Most email providers include some filtering — check whether it is enabled and active",
    whyWeAsk: "Email is the most common delivery mechanism for malware and phishing attacks. Cyber Essentials requires that technical controls are in place to protect against malicious email content.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "mp_mobile_devices_protected",
    sectionId: 4,
    text: "Are mobile phones and tablets used for business protected by anti-malware or equivalent controls?",
    hint: "iOS and Android have built-in protections — check whether they are enabled and supplemented where necessary",
    whyWeAsk: "Mobile devices are increasingly used to access business systems and data. Cyber Essentials requires that mobile devices used for business are included in malware protection controls.",
    type: "radio",
    options: [
      { value: "yes", label: "Yes, mobile devices are protected" },
      { value: "no", label: "No, mobile devices are not protected" },
      { value: "partial", label: "Some mobile devices are protected but not all" },
      { value: "not_applicable", label: "We do not use mobile devices for business" },
    ],
  },
  {
    key: "mp_app_store_only",
    sectionId: 4,
    text: "On mobile devices, are users restricted to installing apps from official app stores only?",
    hint: "Sideloading apps from unofficial sources significantly increases the risk of malware",
    whyWeAsk: "Unofficial apps can contain malware. Cyber Essentials requires that mobile devices used for business only run software from trusted sources such as official app stores.",
    type: "radio",
    options: [
      { value: "yes", label: "Yes, only official app stores are allowed" },
      { value: "no", label: "No, unofficial sources are permitted" },
      { value: "not_applicable", label: "We do not use mobile devices for business" },
      { value: "unsure", label: "I am not sure" },
    ],
  },
  {
    key: "mp_usb_controls",
    sectionId: 4,
    text: "Is the use of USB drives and external storage controlled or restricted?",
    hint: "Uncontrolled USB use is a common malware infection vector",
    whyWeAsk: "USB devices can introduce malware and also cause data loss. Cyber Essentials recommends that removable storage is controlled, particularly on devices handling sensitive data.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "mp_malware_incident_process",
    sectionId: 4,
    text: "Does your organisation have a process for responding if malware is detected on a device?",
    hint: "This does not need to be a formal incident response plan — a simple set of steps is acceptable",
    whyWeAsk: "Knowing what to do when malware is detected limits the damage. A basic incident response process helps contain and recover from malware infections more quickly.",
    type: "radio",
    options: YES_NO_SIMPLE,
  },
  {
    key: "mp_endpoint_management",
    sectionId: 4,
    text: "Are your business devices managed centrally using an MDM or endpoint management tool?",
    hint: "Tools like Microsoft Intune, Jamf, or Google Workspace MDM enable centralised control",
    whyWeAsk: "Centralised device management enables consistent policy enforcement and simplifies malware protection deployment across all devices.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "mp_sandbox_protection",
    sectionId: 4,
    text: "Are email attachments or downloaded files scanned in a sandboxed environment before execution?",
    hint: "Advanced email security tools can execute suspicious attachments safely before delivery",
    whyWeAsk: "Sandboxing provides an additional layer of protection against zero-day malware delivered via email or downloads. While not required for Cyber Essentials, it indicates a strong security posture.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "mp_user_awareness",
    sectionId: 4,
    text: "Are staff trained or made aware of the risks of malware, including phishing and suspicious downloads?",
    hint: "Even basic awareness of common threats helps reduce the risk of successful attacks",
    whyWeAsk: "Human error is involved in most malware infections. User awareness reduces the risk of staff inadvertently triggering a malware infection.",
    type: "radio",
    options: YES_NO,
  },

  // ── Section 5: Security Update Management ────────────────────────────────
  {
    key: "su_updates_applied_promptly",
    sectionId: 5,
    text: "Are security updates applied to devices and software within 14 days of release?",
    hint: "Cyber Essentials requires that critical and high-risk patches are applied within 14 days",
    whyWeAsk: "The majority of successful attacks exploit known vulnerabilities for which patches are already available. Cyber Essentials requires that security updates are applied within 14 days of release.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "su_automatic_updates_enabled",
    sectionId: 5,
    text: "Are automatic updates enabled on devices and key software where possible?",
    hint: "Automatic updates reduce the administrative burden of keeping systems patched",
    whyWeAsk: "Automatic updates ensure patches are applied quickly without relying on manual processes. Cyber Essentials recommends automatic updates where they are available.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "su_operating_systems_supported",
    sectionId: 5,
    text: "Are all operating systems on business devices currently supported and receiving security updates?",
    hint: "Windows 10, Windows 11, macOS 12+, iOS 17+, and Android 13+ are currently supported",
    whyWeAsk: "Unsupported operating systems no longer receive security updates, leaving known vulnerabilities unpatched. Cyber Essentials requires that all in-scope devices run supported operating systems.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "su_software_supported",
    sectionId: 5,
    text: "Is all software installed on business devices currently supported and receiving security updates?",
    hint: "Including browsers, office productivity tools, and any specialist business applications",
    whyWeAsk: "Unsupported software creates known and unpatched vulnerabilities. Cyber Essentials requires that all software in use is actively supported.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "su_firmware_updated",
    sectionId: 5,
    text: "Is the firmware on network devices such as routers and switches kept up to date?",
    hint: "Firmware is the software embedded in hardware — it also requires regular updates",
    whyWeAsk: "Network device firmware vulnerabilities can give attackers significant access to your network. Cyber Essentials includes firmware in scope for update management.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "su_patch_responsibility",
    sectionId: 5,
    text: "Is someone in your organisation responsible for ensuring devices and software are kept up to date?",
    hint: "This could be internal IT staff, an MSP, or a named individual in a small team",
    whyWeAsk: "Without clear ownership, patching tasks can be overlooked. Cyber Essentials requires that there is a clear and accountable process for keeping systems updated.",
    type: "radio",
    options: YES_NO_SIMPLE,
  },
  {
    key: "su_patch_tracking",
    sectionId: 5,
    text: "Do you have a way to track which devices and software have received recent security updates?",
    hint: "This could be a simple spreadsheet or a patch management tool",
    whyWeAsk: "Without visibility of patch status, it is impossible to confirm compliance. Cyber Essentials requires that organisations can demonstrate that updates have been applied.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "su_unsupported_software_process",
    sectionId: 5,
    text: "Do you have a process to identify and remove software that is no longer supported by its vendor?",
    hint: "End-of-life software should be removed, upgraded, or isolated",
    whyWeAsk: "End-of-life software is a persistent vulnerability that cannot be patched. Cyber Essentials requires that unsupported software is removed from in-scope devices.",
    type: "radio",
    options: YES_NO,
  },
  {
    key: "su_app_store_updates",
    sectionId: 5,
    text: "On mobile devices, are apps updated promptly when updates are available?",
    hint: "App stores usually offer automatic updates — check whether they are enabled",
    whyWeAsk: "Mobile applications also receive security updates. Cyber Essentials requires that all in-scope software, including mobile apps, is kept up to date.",
    type: "radio",
    options: [
      { value: "yes", label: "Yes, apps are updated promptly" },
      { value: "no", label: "No, apps are not regularly updated" },
      { value: "not_applicable", label: "We do not use mobile devices for business" },
      { value: "unsure", label: "I am not sure" },
    ],
  },
  {
    key: "su_cloud_software_updated",
    sectionId: 5,
    text: "If you use self-hosted cloud or server software, is it kept up to date with security patches?",
    hint: "This includes web servers, databases, CMS platforms, or self-hosted business tools",
    whyWeAsk: "Self-hosted software requires active patching. If your organisation runs its own servers or cloud infrastructure, security updates must be applied just like on-premises systems.",
    type: "radio",
    options: [
      { value: "yes", label: "Yes, self-hosted software is kept updated" },
      { value: "no", label: "No, it is not regularly updated" },
      { value: "not_applicable", label: "We do not self-host any software" },
      { value: "unsure", label: "I am not sure" },
    ],
  },
  {
    key: "su_patch_testing",
    sectionId: 5,
    text: "Are security patches tested before being applied to critical systems, or are they applied directly?",
    hint: "For most SMEs, applying patches directly is acceptable unless systems are highly critical",
    whyWeAsk: "Patch testing helps prevent operational disruption from problematic updates. However, the risk of not patching usually outweighs the risk of a disruptive update for most SMEs.",
    type: "radio",
    options: [
      { value: "tested_first", label: "Patches are tested first" },
      { value: "applied_directly", label: "Patches are applied directly" },
      { value: "no_process", label: "There is no consistent process" },
      { value: "unsure", label: "I am not sure" },
    ],
  },
  {
    key: "su_update_communication",
    sectionId: 5,
    text: "Are staff informed when important security updates are available or required for their devices?",
    hint: "Good communication helps staff act promptly when updates need to be applied",
    whyWeAsk: "Where updates require user action (such as a laptop restart), clear communication helps ensure updates are applied promptly. This is particularly relevant for remote workers.",
    type: "radio",
    options: YES_NO,
  },
];

export function getQuestionsBySection(sectionId: number): Question[] {
  return QUESTIONS.filter((q) => q.sectionId === sectionId);
}

export function getQuestion(key: string): Question | undefined {
  return QUESTIONS.find((q) => q.key === key);
}

export function getSection(id: number): Section | undefined {
  return SECTIONS.find((s) => s.id === id);
}
